const categories = [
    {
      id: "1",
      title: "Latest News",
      path:"",
      rank: "1",
      type:"news",
      image: "https://www.svgrepo.com/show/13210/flame.svg",
    },
    {
      id: "2",
      title: "Sports",
      path: "sports",
      type:"news",
      rank: "2",
      image: process.env.PUBLIC_URL + '/categories/sports.svg',
    },
    {
      id: "3",
      title: "Entertainment and Media",
      path: "entertainment&media",
      type:"news",
      rank: "3",
      image: process.env.PUBLIC_URL + '/categories/reel.svg',
    },
    {
      id: "4",
      title: "Government Projects and Policies",
      path: "government",
      type:"news",
      rank: "4",
      image: process.env.PUBLIC_URL + '/categories/emblem.svg',
    },
    {
      id: "5",
      title: "Political",
      path: "political",
      type:"news",
      rank: "5",
      image: process.env.PUBLIC_URL + '/categories/town-hall.svg',
    },
    {
      id: "6",
      title: "Finance",
      path: "finance",
      type:"news",
      rank: "6",
      image: process.env.PUBLIC_URL + '/categories/coins.svg',
    },
    {
      id: "7",
      title: "Horoscope",
      path: "horoscope",
      type:"news",
      rank: "7",
      image: process.env.PUBLIC_URL + '/categories/scorpio.svg',
    },
    {
      id: "8",
      title: "Careers",
      path: "careers",
      type:"news",
      rank: "8",
      image: process.env.PUBLIC_URL + '/categories/career.svg',
    },
    {
      id: "9",
      title: "Science and Technology",
      path: "science&tech",
      type:"news",
      rank: "9",
      image: process.env.PUBLIC_URL + '/categories/tech.svg',
    },
    {
      id: "10",
      title: "Healthcare and Wellness",
      path: "health",
      type:"news",
      rank: "10",
      image: process.env.PUBLIC_URL + '/categories/medicines.svg',
    },
    {
      id: "11",
      title: "Latest Publications",
      path:"",
      rank: "11",
      type:"publications",
      image: "https://www.svgrepo.com/show/13210/flame.svg",
    },
    {
      id: "12",
      title: "Archive",
      path:"archive",
      rank: "12",
      type:"publications",
      image: process.env.PUBLIC_URL + '/categories/archive.svg',
    },
    {
      id: "13",
      title: "Others",
      path:"other",
      rank: "13",
      type:"publications",
      image: process.env.PUBLIC_URL + '/categories/file.svg',
    },
    {
      id: "14",
      title: "Others",
      path:"other",
      rank: "14",
      type:"news",
      image: process.env.PUBLIC_URL + '/categories/news.svg',
    }
  ];

export default categories;